### ISSUE TITLE
Rename Package

### ISSUE THREAD

**Issue by logaretm** [ismail9k/vue3-spring#1]
Please consider the name `sosta` 🌀

**Comment by ismail9k** [comment]
I've also thought of names like `ressort`, `yay`, and `trampoline`. But for the Spring-physics animation libraries is more likely to be searched for the "spring" keyword. So, I guess I will stick with this CREATIVE name at least until the library is stable and production-ready.

**Comment by logaretm** [comment]
Alright then 👍
